## Shared runner for tests requiring cross-component or process-level integration.
import integrations/application_sigils
import integrations/figdraw_text_offsets
import integrations/gitprocesslifecycle
import integrations/processdescriptors
import integrations/kosmocliopen
import integrations/kosmoterminalenvironment
import integrations/nativewindowactivation
import integrations/nativewindowlifecycle
import integrations/nativewindowrepaint
import integrations/nativewindowscale
import integrations/urlassets
import integrations/terminals
import integrations/resourcelifetimes
import integrations/backgroundworkershutdown
